### ISSUE TITLE
API Calls not working

### ISSUE THREAD

**Issue by 1Ludwig** [routetonull/getMerakiNeighbor#1]
couldn't get the API call to work with the existing:
meraki.getlldpcdp(apikey,networkid,serial,suppressprint=True)

Instead i got it to working with adding meraki.DashboardAPI instead.

ex.
dashboard = meraki.DashboardAPI(apikey, suppress_logging=True)
orgs = dashboard.organizations.getOrganizations()

**Comment by 1Ludwig** [comment]
All in all you have done a very good job with this one.

**Comment by routetonull** [comment]
Updated the code to work with new [v1 API](https://developer.cisco.com/meraki/api-v1/), should fix API call errors.
